### ISSUE TITLE
NullPointerException on runUiThread

### ISSUE THREAD

**Issue by koenhendriks** [cornedor/mayhem#14]
>java.lang.NullPointerException: Attempt to invoke virtual method 'void >android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
>at nl.deltionmobiel.rooster.ScheduleFragment.noDataAvailable(ScheduleFragment.java:175)
>at nl.deltionmobiel.rooster.Data$1.run(Data.java:143)
>at java.lang.Thread.run(Thread.java:818)

**Comment by cornedor** [comment]
Duplicate of #11
